baseurl = "https://prashantaher70.github.io/"
languageCode = "en-us"
title = "From Mind to Quill"
description = "From Mind to Quill: My experiences and learnings"

disqusShortname = "mindtoquill"
googleAnalytics = "UA-83904648-1"
paginate = 5

[Params]
  favicon = "/images/quill1.png"
  subtitle= "My experiences; My learnings" 
  ogimage= "images/quill.jpeg"
  description = "From Mind to Quill: My experiences and learnings"
  fbappid = "653620094814314"

[Params.fmt]
  ISO8601 = "2006-01-02T15:04:05IST"

[Author]
  name = "Prashant Aher"
  angelco= "prashantaher70"
  github = "prashantaher70"
  linkedin = "prashantaher70"
  email = "aherPrashant70@gmail.com"

[[menu.main]]
  name = "About Me"
  url = "/page/about-me"
  weight = 1
  identifier = "about"  
      
#[[menu.main]]
#  name = "About Me"
#  url = "/about-me"
#  weight = 1
#  parent = "about"  
 
